### ISSUE TITLE
RPM package files permissions are too restrictive

### ISSUE THREAD

**Issue by lbeltrame** [compbio-UofT/savant#16]
The JARs needed by savant are included in folders with too strict permissions:

```
drw-r--r-- 2 root root    4096 21 apr 11.01 lib
drw-r--r-- 2 root root    4096 21 apr 11.01 plugins
-rw-r--r-- 1 root root 1747730 12 nov  2013 savant-core-2.0.5.jar
-rw-r--r-- 1 root root   19331 12 nov  2013 savant.png
```

Notice that `lib` and `plugins` don't have the execution bit set for other, so load will always fail for non-root. Setting those folders' permissions to 755 fixes the issue. 

I didn't manage to find the spec file for the RPM in the source repository, but probably `%defattr` there needs to be adjusted like

```
%defattr (644, root, root, 755)
```

Or individual `%attr` on the affected directoies.

**Comment by sdumitriu** [comment]
Fixed in the sources, but I'm not sure if there will be another Savant release soon.

**Comment by lbeltrame** [comment]
In the mean time I found a *catastrophic* issue in the RPM, probably related to this. After installing (or uninstalling, I noticed only later) Savant, I had my /usr/share/applications permissions set to 744. This broke *a lot* of my system which expected user access (read-only) there.

**Comment by sdumitriu** [comment]
That one should have been fixed as well by the latest commit, sorry for that :(

**Comment by mfiume** [comment]
Ha! Is Savant still being developed?

How are you Sergiu???????? Long time no see man, hope you and the family
are doing well.

Marc
